name: gate_pass_flutter
description: Gate Pass Management System Flutter App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Requests
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # QR Code Generation (for displaying QR codes)
  qr_flutter: ^4.1.0
  
  # QR Code Scanning - ENABLED for camera scanning
  mobile_scanner: ^3.5.6
  
  # Navigation
  go_router: ^12.1.3
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.1.0
  logger: ^2.0.2+1
  
  # Icons
  cupertino_icons: ^1.0.2
  
  # Permissions - REQUIRED for camera access
  permission_handler: ^11.0.1

  # Google Fonts for Poppins font family
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # ADD THIS: App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # FIXED: Enabled assets - removed comment markers
  assets:
    - assets/images/
    - assets/icons/

# MOVED TO CORRECT LOCATION: App icon configuration (at root level, not under flutter:)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  # Optional: Create adaptive icon for Android (recommended)
  adaptive_icon_background: "#FFB703"  # Your app's yellow color
  adaptive_icon_foreground: "assets/images/logo.png"